site.conf: add two more time servers
Freifunk-Rhein-Neckar/site-ffrn pull request #4
Opened 2023-01-15 12:28 UTC by stweil

This makes NTP more robust, so a node can get the
current time even if all servers from ntp.ffrn.de
are down.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

2023-01-15 12:29 UTC, stweil commented
> This makes NTP more robust, so a node can get the current time even if all servers from ntp.ffrn.de are down.

I had to do that on one of my nodes because both NTP servers which are behind ntp.ffrn.de are currently down.

2023-01-15 13:41 UTC, herbetom commented
> I had to do that on one of my nodes because both NTP servers which are behind ntp.ffrn.de are currently down.

I'm not against changing the NTP Servers, hoewer the FFRN NTP Servers aren't down. They just were only rechable from within the FFRN Client networks.

```bash
# ntpdate -q 2a01:4f8:140:4093::2
server 2a01:4f8:140:4093::2, stratum 2, offset -0.000564, delay 0.04149
15 Jan 10:22:30 ntpdate[30574]: adjust time server 2a01:4f8:140:4093::2 offset -0.000564 sec
# ntpdate -q 2a01:4f8:160:624c::2
server 2a01:4f8:160:624c::2, stratum 2, offset -0.001870, delay 0.04407
15 Jan 10:22:44 ntpdate[30618]: adjust time server 2a01:4f8:160:624c::2 offset -0.001870 sec
```

I've also allowed access from outside IPs. But that shouldn't really matter.

2023-01-15 13:49 UTC, stweil commented
I tested yesterday from a FFRN node. It failed with ntp.ffrn.de, and it was successful with de.pool.ntp.org.

2023-01-15 13:55 UTC, stweil commented
The result of a test just now shows that ntp.ffrn.de still fails:

```
root@Ladenburg-INTAKT-001:~# ntpd -d4 -n -q -p ntp.ffrn.de
ntpd: 'ntp.ffrn.de' is 2a01:4f8:140:4093::2
ntpd: sending query to 2a01:4f8:140:4093::2
Alarm clock
```

2023-01-20 10:37 UTC, herbetom requested changes
Both of those zones only have A records. AAAA records are missing.

Our Nodes only have an IPv4 route/address if they've got one from the WAN port.

2023-01-20 11:04 UTC, stweil commented on site.conf
> +    ntp_servers = {'ntp.ffrn.de', '0.freifunk.pool.ntp.org', 'de.pool.ntp.org'},
```suggestion
    ntp_servers = {'ntp.ffrn.de', '2.freifunk.pool.ntp.org', '2.de.pool.ntp.org'},
```

2023-01-20 11:06 UTC, stweil commented on site.conf
> +    ntp_servers = {'ntp.ffrn.de', '0.freifunk.pool.ntp.org', 'de.pool.ntp.org'},
According to https://linuxreviews.org/IPv6-listening_NTP_servers, the NTP pools starting with 2 point to IPv6-ready servers. Both updated names provide indeed IPv6 addresses in addition it IPv4 addresses.

2023-01-20 12:00 UTC, stweil commented
> Both of those zones only have A records. AAAA records are missing.

That's fixed now.

2023-01-21 16:28 UTC, herbetom approved these changes

2023-01-21 16:29 UTC, merged

2023-01-21 16:32 UTC, herbetom commented
I still don't think that both servers were generally unrachable. But it also shouldn't do much harm and with the pool addresses it should be possible to obtain a correct time even if the fastd tunnel fails for some reason. 

Thanks for contributing :)